CLINC = $(CUDA)/include/
CLLIB = $(CUDA)/lib/ -l OpenCL


_DEPS = oclutil.h
_OBJS = oclutil.o reduce.o


IDIR =.
ODIR=nvidia
DEPS = $(patsubst %,$(IDIR)/%,$(_DEPS))
OBJS = $(patsubst %,$(ODIR)/%,$(_OBJS))
CC=gcc


all: $(ODIR)/reduce makefile.nvidia

# put executable here
$(ODIR)/reduce: $(OBJS)
	gcc -o $@ $^ -L $(CLLIB) $(MACRODEF)

$(ODIR)/%.o: %.c $(DEPS)
	mkdir -p $(ODIR)
	$(CC) -c -o $@ $< -I $(CLINC) $(MACRODEF)

.PHONY: clean

clean:
	rm -f $(ODIR)/*.o *~ $(INCDIR)/*~ 



